@endpoint = https://localhost:16002

###

# @name getAllPortfolios
GET {{endpoint}}/portfolios

###

# @name createPortfolio
POST {{endpoint}}/portfolios
Content-Type: application/json

{
  "name": "My Portfolio"
}

###

# @name getPortfolioById
GET {{endpoint}}/portfolios/{{createPortfolio.response.body.$.id}}

###

# @name deletePortfolio
DELETE {{endpoint}}/portfolios/{{createPortfolio.response.body.$.id}}

###

# @name createHolding
POST {{endpoint}}/holdings
Content-Type: application/json

{
  "portfolioId": "{{createPortfolio.response.body.$.id}}",
  "exchange": "XETRA",
  "ticker": "EUNL",
  "name": "iShares Core MSCI World UCITS ETF USD (Acc)",
  "type": "ETF"
}

###

# @name deleteHolding
DELETE {{endpoint}}/holdings/{{createHolding.response.body.$.id}}

###

# @name createTransaction
POST {{endpoint}}/transactions
Content-Type: application/json

{
  "portfolioId": "{{createPortfolio.response.body.$.id}}",
  "holdingId": "{{createHolding.response.body.$.id}}",
  "type": "Buy",
  "quantity": 100,
  "date": "{{$datetime iso8601}}",
  "price": 104.05
}

###

# @name deleteTransaction
DELETE {{endpoint}}/transactions/{{createTransaction.response.body.$.id}}
