# @name getAllPortfolios
GET http://localhost:5197/portfolios

###

# @name createPortfolio
POST http://localhost:5197/portfolios
Content-Type: application/json

{
  "name": "My Portfolio"
}

###

# @name getPortfolioById
GET http://localhost:5197/portfolios/{{createPortfolio.response.body.$.id}}

###

# @name deletePortfolio
DELETE http://localhost:5197/portfolios/{{createPortfolio.response.body.$.id}}

###

# @name createHolding
POST http://localhost:5197/holdings
Content-Type: application/json

{
  "portfolioId": "{{createPortfolio.response.body.$.id}}",
  "exchange": "XETRA",
  "ticker": "EUNL",
  "name": "iShares Core MSCI World UCITS ETF USD (Acc)",
  "type": "ETF"
}

###

# @name deleteHolding
DELETE http://localhost:5197/holdings/{{createHolding.response.body.$.id}}

###

# @name createTransaction
POST http://localhost:5197/transactions
Content-Type: application/json

{
  "portfolioId": "{{createPortfolio.response.body.$.id}}",
  "holdingId": "{{createHolding.response.body.$.id}}",
  "type": "Buy",
  "quantity": 100,
  "date": "2025-01-01T00:00:00Z",
  "price": 537.61
}

###

# @name deleteTransaction
DELETE http://localhost:5197/transactions/{{createTransaction.response.body.$.id}}
