global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using Portfoli.Api.Endpoints;
global using Portfoli.Domain.Portfolios;
global using Portfoli.Domain.Shared;
global using Portfoli.Domain.Transactions;
global using Portfoli.Infra;
global using static Portfoli.Api.ErrorFactory;
