name: Continuous integration

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet build src/server/Portfoli.slnx
